In [9]:
from google.cloud import bigquery
import pandas as pd
import numpy as  np
import matplotlib.pyplot as  plt
import polars as pl
import os

In [10]:
os.environ["GOOGLE_APPLICATION_CREDENTIALS"]=r'C:\Users\QC#\Downloads\dbt-learning-493706-81ad6e669580.json'
client=bigquery.Client()

In [12]:
df1="""
select * from `dbt-learning-493706.raw_bikeshare_trips.raw_region`
"""
raw_region=pl.from_arrow(client.query(df1).result().to_arrow()
                        )

In [13]:
df2="""
select * from `dbt-learning-493706.raw_bikeshare_trips.raw_stations`
"""
raw_stations=pl.from_arrow(client.query(df2).result().to_arrow()
                          )

<sys>:0: UserWarning: Extension type 'google:sqlType:geography' is not registered; loading as its storage type.

To avoid this warning, register the extension type or set environment variable 'POLARS_UNKNOWN_EXTENSION_TYPE_BEHAVIOR' to 'load_as_storage' or 'load_as_extension'.

In Polars 2.0, the default behavior will change to 'load_as_extension'.

In [14]:
df3="""
select * from `dbt-learning-493706.raw_bikeshare_trips.raw_trips`
"""
raw_trips=pl.from_arrow(client.query(df3).result().to_arrow()
                       )

In [16]:
raw_trips=raw_trips.to_pandas()

In [17]:
raw_trips

,trip_id,duration_sec,start_date,start_station_name,start_station_id,end_date,end_station_name,end_station_id,bike_number,zip_code,...,c_subscription_type,start_station_latitude,start_station_longitude,end_station_latitude,end_station_longitude,member_birth_year,member_gender,bike_share_for_all_trip,start_station_geom,end_station_geom
0,20171112084953927,13392,2017-11-12 08:49:53+00:00,10th St at Fallon St,201,2017-11-12 12:33:05+00:00,10th St at Fallon St,201,927,None,...,None,37.797673,-122.262997,37.797673,-122.262997,NaN,None,None,POINT(-122.2629973 37.7976728),POINT(-122.2629973 37.7976728)
1,201711171901012565,179,2017-11-17 19:01:01+00:00,10th St at Fallon St,201,2017-11-17 19:04:01+00:00,12th St at 4th Ave,233,2565,None,...,None,37.797673,-122.262997,37.795812,-122.255555,1993.0,Male,None,POINT(-122.2629973 37.7976728),POINT(-122.2555549 37.7958125)
2,2018010314142731,288,2018-01-03 14:14:27+00:00,10th St at Fallon St,201,2018-01-03 14:19:16+00:00,12th St at 4th Ave,233,31,None,...,None,37.797673,-122.262997,37.795812,-122.255555,1960.0,Male,Yes,POINT(-122.2629973 37.7976728),POINT(-122.2555549 37.7958125)
3,201803171330131950,277,2018-03-17 13:30:13+00:00,10th St at Fallon St,201,2018-03-17 13:34:50+00:00,12th St at 4th Ave,233,1950,None,...,None,37.797673,-122.262997,37.795812,-122.255555,1980.0,Male,No,POINT(-122.2629973 37.7976728),POINT(-122.2555549 37.7958125)
4,20180412224316935,222,2018-04-12 22:43:16+00:00,10th St at Fallon St,201,2018-04-12 22:46:58+00:00,12th St at 4th Ave,233,935,None,...,None,37.797673,-122.262997,37.795812,-122.255555,1977.0,Male,No,POINT(-122.2629973 37.7976728),POINT(-122.2555549 37.7958125)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1947412,546126,3919,2014-11-15 18:16:00+00:00,Yerba Buena Center of the Arts (3rd @ Howard),68,2014-11-15 19:21:00+00:00,Yerba Buena Center of the Arts (3rd @ Howard),68,571,92114,...,Customer,NaN,NaN,NaN,NaN,NaN,None,None,None,None
1947413,106492,64,2013-11-24 17:45:00+00:00,Yerba Buena Center of the Arts (3rd @ Howard),68,2013-11-24 17:46:00+00:00,Yerba Buena Center of the Arts (3rd @ Howard),68,614,94103,...,Subscriber,NaN,NaN,NaN,NaN,NaN,None,None,None,None
1947414,483333,60,2014-10-04 19:21:00+00:00,Yerba Buena Center of the Arts (3rd @ Howard),68,2014-10-04 19:22:00+00:00,Yerba Buena Center of the Arts (3rd @ Howard),68,560,nil,...,Customer,NaN,NaN,NaN,NaN,NaN,None,None,None,None
1947415,84307,509,2013-11-05 14:02:00+00:00,Yerba Buena Center of the Arts (3rd @ Howard),68,2013-11-05 14:11:00+00:00,Yerba Buena Center of the Arts (3rd @ Howard),68,481,94022,...,Subscriber,NaN,NaN,NaN,NaN,NaN,None,None,None,None
1947416,517775,452,2014-10-27 18:18:00+00:00,Yerba Buena Center of the Arts (3rd @ Howard),68,2014-10-27 18:25:00+00:00,Yerba Buena Center of the Arts (3rd @ Howard),68,467,30240,...,Customer,NaN,NaN,NaN,NaN,NaN,None,None,None,None

In [18]:
raw_stations=raw_stations.to_pandas()

In [19]:
raw_region=raw_region.to_pandas()

In [21]:
raw_region

   region_id           name
0          3  San Francisco
1          5       San Jose
2         14       Berkeley
3         12        Oakland
4         23             8D
5         13     Emeryville

In [20]:
raw_stations

,station_id,name,short_name,lat,lon,region_id,rental_methods,capacity,external_id,eightd_has_key_dispenser,has_kiosk,station_geom
0,505,Geneva Ave at Moscow St,SF-CC18,37.713193,-122.433491,NaN,None,0,None,None,False,POINT(-122.433491349 37.713192538)
1,539,North Point St at Divisadero St,SF-A18,37.802949,-122.442702,NaN,None,0,None,None,False,POINT(-122.442702 37.802949)
2,535,Filbert St at Fillmore St,SF-C19,37.798014,-122.435562,NaN,None,0,None,None,True,POINT(-122.435562 37.798014)
3,504,Onondaga Ave at Alemany Blvd,SF-AA17,37.721544,-122.438303,NaN,None,0,None,None,False,POINT(-122.438303232 37.721543666)
4,523,Lafayette Park (Laguna St at Washington St),SF-E21,37.791966,-122.429315,NaN,None,0,None,None,False,POINT(-122.429315 37.791966)
...,...,...,...,...,...,...,...,...,...,...,...,...
467,253,Haste St at College Ave,BK-E10,37.866418,-122.253799,14.0,None,23,None,None,True,POINT(-122.253799438 37.866417941)
468,246,Berkeley Civic Center,BK-D7-2,37.869060,-122.270556,14.0,None,27,None,None,True,POINT(-122.270556 37.8690599)
469,250,North Berkeley BART Station,BK-C5,37.873558,-122.283093,14.0,None,27,None,None,True,POINT(-122.283093 37.873558)
470,245,Downtown Berkeley BART,BK-D7-1,37.870139,-122.268422,14.0,None,29,None,None,True,POINT(-122.268422 37.870139)
471,243,Bancroft Way at College Ave,BK-D10,37.869360,-122.254337,14.0,None,30,None,None,True,POINT(-122.2543374 37.8693603)

In [24]:
raw_region.columns

Index(['region_id', 'name'], dtype='object')

In [25]:
raw_stations.columns

Index(['station_id', 'name', 'short_name', 'lat', 'lon', 'region_id',
       'rental_methods', 'capacity', 'external_id', 'eightd_has_key_dispenser',
       'has_kiosk', 'station_geom'],
      dtype='object')

In [26]:
raw_trips.columns

Index(['trip_id', 'duration_sec', 'start_date', 'start_station_name',
       'start_station_id', 'end_date', 'end_station_name', 'end_station_id',
       'bike_number', 'zip_code', 'subscriber_type', 'c_subscription_type',
       'start_station_latitude', 'start_station_longitude',
       'end_station_latitude', 'end_station_longitude', 'member_birth_year',
       'member_gender', 'bike_share_for_all_trip', 'start_station_geom',
       'end_station_geom'],
      dtype='object')

In [30]:
raw_trips.isnull().sum()

trip_id                          0
duration_sec                     0
start_date                       0
start_station_name               0
start_station_id                 0
end_date                         0
end_station_name                 0
end_station_id                   0
bike_number                      0
zip_code                    970581
subscriber_type                  0
c_subscription_type         963771
start_station_latitude      983646
start_station_longitude     983646
end_station_latitude        983646
end_station_longitude       983646
member_birth_year          1084531
member_gender              1084304
bike_share_for_all_trip    1503346
start_station_geom          983646
end_station_geom            983646
dtype: int64

In [32]:
raw_trips.dtypes

trip_id                                 object
duration_sec                             int64
start_date                 datetime64[us, UTC]
start_station_name                      object
start_station_id                         int64
end_date                   datetime64[us, UTC]
end_station_name                        object
end_station_id                           int64
bike_number                              int64
zip_code                                object
subscriber_type                         object
c_subscription_type                     object
start_station_latitude                 float64
start_station_longitude                float64
end_station_latitude                   float64
end_station_longitude                  float64
member_birth_year                      float64
member_gender                           object
bike_share_for_all_trip                 object
start_station_geom                      object
end_station_geom                        object
dtype: object

In [34]:
raw_stations.isnull().sum()

station_id                    0
name                          0
short_name                    0
lat                           0
lon                           0
region_id                     9
rental_methods              472
capacity                      0
external_id                 472
eightd_has_key_dispenser    472
has_kiosk                     0
station_geom                  0
dtype: int64

In [35]:
raw_stations.dtypes

station_id                   object
name                         object
short_name                   object
lat                         float64
lon                         float64
region_id                   float64
rental_methods               object
capacity                      int64
external_id                  object
eightd_has_key_dispenser     object
has_kiosk                      bool
station_geom                 object
dtype: object

In [36]:
raw_region.isna().sum()

region_id    0
name         0
dtype: int64

In [37]:
raw_region.dtypes

region_id     int64
name         object
dtype: object